apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: configmap-example
spec:
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example-app
          image: localhost:5000/configmap-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
      volumes:
        - name: config-volume
          configMap:
            name: example-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: example
  replicas: 2 # tells deployment to run 2 pods matching the template
