apiVersion: v1
kind: Pod
metadata:
  name: "hello-world"
  labels:
    app: "hello-world"
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
spec:
  template:
    metadata:
      name: "hello-world"
      labels:
        app: "hello-world"
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: front-end
