apiVersion: v1
kind: ReplicationController
metadata:
  name:  myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: "hello-world"
      labels:
        app: "hello-world"
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
